version: '3'

networks:
  web:
    external: true
  backend:

volumes:
  <DATABASE-VOLUME-NAME>:
    external: true

services:
  php:
    build: ./php
    depends_on:
    - database
    networks:
    - web
    - backend
    env_file: config.env
    expose:
    - "80"
    volumes:
    - ./www:/var/www/html:rw
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:<HOSTNAME>"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
    restart: unless-stopped

  front-redirector:
    image: schmunk42/nginx-redirect:latest
    networks:
    - web
    expose:
    - "80"
    environment:
    - "SERVER_REDIRECT=<OTHERHOSTNAME>"
    - "SERVER_REDIRECT_SCHEME=https"
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:<HOSTNAME>"
    - "traefik.frontend.entryPoints=http,https"
    restart: unless-stopped

  database:
    image: mysql:5.7.29
    networks:
    - backend
    env_file: config.env
    volumes:
    - <DATABASE-VOLUME-NAME>:/var/lib/mysql:rw
    restart: unless-stopped

  database-manager:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - database
    networks:
    - web
    - backend
    env_file: config.env
    environment:
    - "PMA_HOST=database"
    - "PMA_ABSOLUTE_URI=https://<HOSTNAME>/phpmyadmin/"
    expose:
    - "80"
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:<HOSTNAME>;PathPrefixStrip:/phpmyadmin"
    - "traefik.frontend.entryPoints=http,https"
    - "traefik.frontend.redirect.entryPoint=https"
    restart: unless-stopped

  ftp:
    image: delfer/alpine-ftp-server:latest
    networks:
    - web
    volumes:
    - ./www:/data:rw
    ports:
    - "2121:21"
    - "21000-21010:21000-21010"
    environment:
    - "USERS=<FTPUSER>|<FTPPASSWORD>|/data"
    - "MIN_PORT=21000"
    - "MAX_PORT=21010"
    restart: unless-stopped
